create table "public"."note_template" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "template" text,
    "public" boolean,
    "user_id" uuid
);


alter table "public"."note_template" enable row level security;

CREATE UNIQUE INDEX note_template_pkey ON public.note_template USING btree (id);

alter table "public"."note_template" add constraint "note_template_pkey" PRIMARY KEY using index "note_template_pkey";


