create table "public"."user_settings" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now(),
    "key" text,
    "value" text
);


alter table "public"."user_settings" enable row level security;

CREATE UNIQUE INDEX user_settings_pkey ON public.user_settings USING btree (id);

alter table "public"."user_settings" add constraint "user_settings_pkey" PRIMARY KEY using index "user_settings_pkey";


